import { useEffect, useState } from 'react';
import { money, supabase } from './lib/supabase';

export default function App(){
 const [user,setUser]=useState(null),[products,setProducts]=useState([]),[packages,setPackages]=useState([]),[payments,setPayments]=useState([]),[cart,setCart]=useState([]),[tab,setTab]=useState('Home'),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 const notify=x=>{setMessage(x);setTimeout(()=>setMessage(''),2500)};
 const ensureProfile=async u=>{if(u&&supabase) await supabase.rpc('ensure_customer_profile',{p_full_name:u.user_metadata?.full_name||'',p_phone:u.user_metadata?.phone||''});};
 const load=async()=>{if(!supabase){setLoading(false);return}const [p,w,pm,s]=await Promise.all([supabase.from('electronics_products').select('*,electronics_categories(name)').eq('is_active',true),supabase.from('wedding_packages').select('*').eq('is_active',true),supabase.from('payment_methods').select('*').eq('is_enabled',true),supabase.auth.getSession()]);if(p.error||w.error){notify('Unable to load ZIA data');setLoading(false);return}setProducts((p.data||[]).map(x=>({...x,category:x.electronics_categories?.name||'Smart Gadget Store'})));setPackages(w.data||[]);setPayments(pm.data||[]);setUser(s.data.session?.user||null);await ensureProfile(s.data.session?.user);setLoading(false)};
 useEffect(()=>{load();if(!supabase)return;const auth=supabase.auth.onAuthStateChange(async(_e,s)=>{setUser(s?.user||null);await ensureProfile(s?.user)});const channel=supabase.channel('customer-catalog').on('postgres_changes',{event:'*',schema:'public',table:'electronics_products'},load).on('postgres_changes',{event:'*',schema:'public',table:'wedding_packages'},load).on('postgres_changes',{event:'*',schema:'public',table:'payment_methods'},load).subscribe();return()=>{auth.data.subscription.unsubscribe();supabase.removeChannel(channel)}},[]);
 const add=p=>setCart(c=>{const old=c.find(x=>x.id===p.id);return old?c.map(x=>x.id===p.id?{...x,quantity:Math.min(x.quantity+1,p.stock_quantity)}:x):[...c,{...p,quantity:1}]});
 const checkout=async e=>{e.preventDefault();if(!user)return notify('Please sign in first');const f=new FormData(e.currentTarget);const {error}=await supabase.rpc('checkout_cart',{p_items:cart.map(x=>({product_id:x.id,quantity:x.quantity})),p_payment_method_id:f.get('payment_method_id'),p_delivery_address:f.get('address')});if(error)notify(error.message);else{setCart([]);setTab('Orders');notify('Order placed successfully')}};
 if(loading)return <main className="app-shell"><div className="state-card">Loading ZIA Event and Wedding Planner…</div></main>;
 return <main className="app-shell"><header className="topbar"><div className="brand-mark">Z</div><div><p className="eyebrow">Event and Wedding Planner</p><h1>ZIA Event and Wedding Planner</h1></div></header><nav className="nav-bar">{['Home','Wedding & Events','Smart Gadget Store','Cart','Orders','Account'].map(x=><button className={tab===x?'nav-item active':'nav-item'} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav>{tab==='Home'&&<><section className="hero-card"><p className="eyebrow">Premium experiences</p><h2>Celebrate beautifully. Shop smarter.</h2><button onClick={()=>setTab('Wedding & Events')}>Plan an event</button></section><h3>Smart Gadget Store</h3><div className="card-grid">{products.slice(0,4).map(p=><Product p={p} add={()=>add(p)} key={p.id}/>)}</div></>}{tab==='Smart Gadget Store'&&<><h2>Smart Gadget Store</h2><div className="card-grid">{products.map(p=><Product p={p} add={()=>add(p)} key={p.id}/>)}</div></>}{tab==='Wedding & Events'&&<section className="panel-block"><h2>Wedding & Event Packages</h2>{packages.map(p=><div className="detail-row" key={p.id}><div><b>{p.title}</b><p>{p.description}</p></div><strong>{money(p.price)}</strong></div>)}</section>}{tab==='Cart'&&<section className="panel-block"><h2>Cart</h2>{cart.map(x=><div className="detail-row" key={x.id}><span>{x.name} × {x.quantity}</span><b>{money(x.price*x.quantity)}</b></div>)}{cart.length?<form className="form-grid" onSubmit={checkout}><textarea name="address" required minLength="8" placeholder="Delivery address"/><select name="payment_method_id" required><option value="">Payment method</option>{payments.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><button className="primary-full">Checkout</button></form>:<p>Your cart is empty.</p>}</section>}{tab==='Orders'&&<section className="panel-block"><h2>Order history</h2>{user?<OrderHistory user={user}/>:<p>Sign in to view orders.</p>}</section>}{tab==='Account'&&<Account user={user} setUser={setUser} notify={notify}/>} {message&&<div className="toast">{message}</div>}</main>}
function Product({p,add}){return <article className="listing-card"><div className="card-body"><span className="tag">{p.category}</span><h3>{p.name}</h3><p>{p.description}</p><strong>{money(p.price)}</strong><button onClick={add} disabled={!p.stock_quantity}>Add to cart</button></div></article>}
function OrderHistory({user}){const [rows,setRows]=useState([]);useEffect(()=>{supabase.from('orders').select('*,order_items(*)').eq('customer_id',user.id).order('created_at',{ascending:false}).then(({data})=>setRows(data||[]))},[user.id]);return rows.length?rows.map(x=><div className="detail-row" key={x.id}><span>{x.id}</span><b>{money(x.total)} · {x.status}</b></div>):<p>No orders yet.</p>}
function Account({user,setUser,notify}){const sign=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const {data,error}=await supabase.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(error)notify(error.message);else{setUser(data.user);notify('Signed in')}};return <section className="panel-block">{user?<><h2>My account</h2><p>{user.email}</p><button onClick={()=>supabase.auth.signOut()}>Sign out</button></>:<form className="form-grid" onSubmit={sign}><h2>Customer sign in</h2><input name="email" type="email" required placeholder="Email"/><input name="password" type="password" required minLength="8" placeholder="Password"/><button className="primary-full">Sign in</button></form>}</section>}
